@BASE_URL = http://localhost:3000/api/v1
@CODE= 727538
@VERIFY_TOKEN=06f6ac1036a91a4616ed70d7a3ff86e74018a69ab7667d59612c6d6720167a36
@RESET_TOKEN=60c58d88ecfba2ac252095c3d242a0ba9080daea6bf4666663138d6dc42844ae

@ACCESS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTk0N2RhNDkzZjFlZWNlOWVkMWI0NGUiLCJzZXNzaW9uSWQiOiI2YTk0N2RkYzkzZjFlZWNlOWVkMWI0NGYiLCJpYXQiOjE3ODgxMTY0NDQsImV4cCI6MTc4ODExNzM0NCwiYXVkIjoidXNlciIsImlzcyI6Im1lcm4tYXV0aC1sYWIifQ.rsXDAUF7VFtcUiSucttTnZXHRKHro-jkvIuzmi-xg6s

### Register

POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "name":"John Doe",
    "email":"cexehox721@robustq.com",
    "password":"password123"
}

### Login

POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email":"cexehox721@robustq.com",
    "password":"password123"
}

### Refresh

POST {{BASE_URL}}/auth/refresh
Content-Type: application/json


#### Logout

POST {{BASE_URL}}/auth/logout
Content-Type: application/json


#### Get User Profile

GET {{BASE_URL}}/auth/me


### Verify Email - Code

POST {{BASE_URL}}/auth/verify-email/code
Content-Type: application/json

{
    "email": "cexehox721@robustq.com",
    "code": "{{CODE}}"
}


### Verify Email - Link

GET {{BASE_URL}}/auth/verify-email/link?token={{VERIFY_TOKEN}}


#### Forgot Password

POST {{BASE_URL}}/auth/forgot-password
Content-Type: application/json

{
    "email": "cexehox721@robustq.com"
}


### Reset Password

POST {{BASE_URL}}/auth/reset-password
Content-Type: application/json

{
    "token": "{{RESET_TOKEN}}",
    "password": "newpassword123"
}


#### Change Password

POST {{BASE_URL}}/auth/change-password
Content-Type: application/json

{
    "oldPassword": "password123",
    "newPassword": "newpassword123"
}



### Google OAuth

GET {{BASE_URL}}/auth/google


#### Github OAuth

GET {{BASE_URL}}/auth/github



### Setup TOTP

POST {{BASE_URL}}/2fa/setup-totp
Content-Type: application/json
Cookie: accessToken=


